# verified on https://config.travis-ci.com/explore
language: rust
os: linux
dist: xenial
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
jobs:
  include:
    - rust: stable
      before_install:
        - sudo apt-get update
        - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - sudo apt-get install -y nodejs yarn
      script:
        - yarn
        - yarn lint
        - cargo update
        - cargo check --all --no-default-features
        - cargo test --all-features --all -- --nocapture
        - cd actors-macros; cargo test --no-default-features -- --nocapture; cd ..
