# verified on https://config.travis-ci.com/explore
language: rust
os: linux
dist: xenial
jobs:
  include:
    - rust: stable
script:
  - yarn
  - yarn lint
  - cargo update
  - cargo check --all --no-default-features
  - cargo test --all-features --all -- --nocapture
  - cd actors-macros; cargo test --no-default-features -- --nocapture; cd ..
