# verified on https://config.travis-ci.com/explore
language: rust
os: linux
dist: xenial
jobs:
  include:
    - rust: stable
      script:
        - cargo update
        - cargo check --all --no-default-features
        - cargo test --all-features --all -- --nocapture
        - cd actors-macros; cargo test --no-default-features -- --nocapture; cd ..
    - name: 'pre-commit'
      language: python
      python: '3.7'
      before_install:
        - |
          pip3 install pre-commit
      script:
        - pre-commit run -a
